// Writes web/generated.js from the compiled vault and the TierLogic circuit so the
// static web app has the ABI, bytecode and netlist without a bundler.
// Run after `npx hardhat compile`:  node scripts/build-web.js
const fs = require('fs');
const path = require('path');
const tier = require('../circuit/tierLogic');
const { XLAYER, FACTORY_ABI, CIRCUITS_ABI, TRANSISTORS_ABI } = require('./tapeout');

const artifact = require('../artifacts/contracts/CircuitVault.sol/CircuitVault.json');

const out = `// Generated by scripts/build-web.js. Do not edit by hand.
export const XLAYER = ${JSON.stringify({ ...XLAYER, deployFee: String(XLAYER.deployFee), protocolFee: String(XLAYER.protocolFee), tapeoutFee: String(XLAYER.tapeoutFee) }, null, 2)};
export const FACTORY_ABI = ${JSON.stringify(FACTORY_ABI, null, 2)};
export const CIRCUITS_ABI = ${JSON.stringify(CIRCUITS_ABI, null, 2)};
export const TRANSISTORS_ABI = ${JSON.stringify(TRANSISTORS_ABI, null, 2)};
export const TIER = ${JSON.stringify({ netlistHex: tier.netlistHex, nIn: tier.N_IN, nOut: tier.N_OUT, gates: tier.gateCount, nNand: tier.nNand, nLatch: tier.nLatch })};
export const VAULT_ABI = ${JSON.stringify(artifact.abi)};
export const VAULT_BYTECODE = ${JSON.stringify(artifact.bytecode)};
`;

const root = path.join(__dirname, '..');
const dest = path.join(root, 'web', 'generated.js');
fs.mkdirSync(path.dirname(dest), { recursive: true });
fs.writeFileSync(dest, out);
console.log(`wrote ${path.relative(process.cwd(), dest)} (${out.length} bytes)`);

// Copy the browser-safe Copilot compiler (no LLM, no Node APIs) and its examples
// into web/vendor/, keeping the same relative layout so imports resolve unchanged.
const VENDOR = [
  'circuit/netlist.mjs',
  'copilot/expr.mjs',
  'copilot/spec.mjs',
  'copilot/table.mjs',
  'copilot/verify.mjs',
  'copilot/synth.mjs',
];
const vendor = path.join(root, 'web', 'vendor');
fs.rmSync(vendor, { recursive: true, force: true });
for (const rel of VENDOR) {
  const to = path.join(vendor, rel);
  fs.mkdirSync(path.dirname(to), { recursive: true });
  fs.writeFileSync(to, `// Copied from ${rel} by scripts/build-web.js. Do not edit here.\n` + fs.readFileSync(path.join(root, rel), 'utf8'));
}
const examples = Object.fromEntries(
  fs.readdirSync(path.join(root, 'copilot', 'examples')).sort().map((f) => [
    f.replace(/\.json$/, ''),
    JSON.parse(fs.readFileSync(path.join(root, 'copilot', 'examples', f), 'utf8')),
  ]),
);
fs.writeFileSync(path.join(vendor, 'examples.js'), `// Generated by scripts/build-web.js from copilot/examples/.\nexport const EXAMPLES = ${JSON.stringify(examples, null, 2)};\n`);
console.log(`copied ${VENDOR.length} modules and ${Object.keys(examples).length} examples to web/vendor/`);

// Cache busting: stamp every local script and the stylesheet with a content
// hash so a deploy never mixes a fresh app.js with a cached core.js. Module
// imports resolve through an import map, so the source files stay unchanged.
const crypto = require('crypto');
const webDir = path.join(root, 'web');
const hashOf = (rel) => crypto.createHash('sha256').update(fs.readFileSync(path.join(webDir, rel))).digest('hex').slice(0, 10);
const walk = (dir) => fs.readdirSync(dir, { withFileTypes: true }).flatMap((d) => {
  const full = path.join(dir, d.name);
  return d.isDirectory() ? walk(full) : [path.relative(webDir, full).split(path.sep).join('/')];
});
const modules = walk(webDir).filter((f) => /\.(m?js)$/.test(f) && f !== 'package.json').sort();
const imports = Object.fromEntries(modules.map((f) => [`./${f}`, `./${f}?v=${hashOf(f)}`]));
const indexPath = path.join(webDir, 'index.html');
let html = fs.readFileSync(indexPath, 'utf8');
const map = `<!-- importmap:start (generated by scripts/build-web.js) -->\n  <script type="importmap">${JSON.stringify({ imports })}</script>\n  <!-- importmap:end -->`;
html = html.replace(/<!-- importmap:start[\s\S]*?<!-- importmap:end -->/, map);
html = html.replace(/<script type="module" src="app\.js(\?v=[0-9a-f]+)?"><\/script>/, `<script type="module" src="app.js?v=${hashOf('app.js')}"></script>`);
html = html.replace(/<link rel="stylesheet" href="style\.css(\?v=[0-9a-f]+)?" \/>/, `<link rel="stylesheet" href="style.css?v=${hashOf('style.css')}" />`);
fs.writeFileSync(indexPath, html);
console.log(`stamped ${modules.length} modules + style.css with content hashes in web/index.html`);
