// Writes web/generated.js from the compiled vault and the TierLogic circuit so the
// static web app has the ABI, bytecode and netlist without a bundler.
// Run after `npx hardhat compile`:  node scripts/build-web.js
const fs = require('fs');
const path = require('path');
const tier = require('../circuit/tierLogic');
const { XLAYER, FACTORY_ABI, CIRCUITS_ABI, TRANSISTORS_ABI } = require('./tapeout');

const artifact = require('../artifacts/contracts/CircuitVault.sol/CircuitVault.json');

const out = `// Generated by scripts/build-web.js. Do not edit by hand.
export const XLAYER = ${JSON.stringify({ ...XLAYER, deployFee: String(XLAYER.deployFee), protocolFee: String(XLAYER.protocolFee), tapeoutFee: String(XLAYER.tapeoutFee) }, null, 2)};
export const FACTORY_ABI = ${JSON.stringify(FACTORY_ABI, null, 2)};
export const CIRCUITS_ABI = ${JSON.stringify(CIRCUITS_ABI, null, 2)};
export const TRANSISTORS_ABI = ${JSON.stringify(TRANSISTORS_ABI, null, 2)};
export const TIER = ${JSON.stringify({ netlistHex: tier.netlistHex, nIn: tier.N_IN, nOut: tier.N_OUT, gates: tier.gateCount, nNand: tier.nNand, nLatch: tier.nLatch })};
export const VAULT_ABI = ${JSON.stringify(artifact.abi)};
export const VAULT_BYTECODE = ${JSON.stringify(artifact.bytecode)};
`;

const dest = path.join(__dirname, '..', 'web', 'generated.js');
fs.mkdirSync(path.dirname(dest), { recursive: true });
fs.writeFileSync(dest, out);
console.log(`wrote ${path.relative(process.cwd(), dest)} (${out.length} bytes)`);
